use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use chrono::{Duration, NaiveDate};

use crate::calendar::ExchangeCalendar;

#[derive(Debug, Clone)]
pub struct SynthDatasetRequest {
    pub output_dir: PathBuf,
    pub start_date: NaiveDate,
    pub end_date: NaiveDate,
    pub seed: u64,
    pub us_symbols: usize,
    pub a_symbols: usize,
    pub jp_symbols: usize,
    pub industries_per_market: usize,
    pub force: bool,
}

pub fn generate_synth_dataset(req: &SynthDatasetRequest) -> Result<()> {
    if req.start_date > req.end_date {
        return Err(anyhow!("start_date must be <= end_date"));
    }
    if req.industries_per_market == 0 {
        return Err(anyhow!("industries_per_market must be > 0"));
    }
    if req.us_symbols == 0 || req.a_symbols == 0 || req.jp_symbols == 0 {
        return Err(anyhow!("symbol counts must be > 0 for each market"));
    }

    let out = &req.output_dir;
    fs::create_dir_all(out)?;

    let files = [
        out.join("us_equities.csv"),
        out.join("a_share.csv"),
        out.join("jp_equities.csv"),
        out.join("us_industries.csv"),
        out.join("a_industries.csv"),
        out.join("jp_industries.csv"),
    ];
    if !req.force {
        for f in &files {
            if f.exists() {
                return Err(anyhow!(
                    "refusing to overwrite existing file (pass --force): {}",
                    f.display()
                ));
            }
        }
    }

    let cal = ExchangeCalendar::new();
    let mut rng = SplitMix64::new(req.seed);

    let specs = [
        MarketSpec {
            market: "US",
            symbols: req.us_symbols,
            industries: req.industries_per_market,
            bars_path: out.join("us_equities.csv"),
            industries_path: out.join("us_industries.csv"),
        },
        MarketSpec {
            market: "A",
            symbols: req.a_symbols,
            industries: req.industries_per_market,
            bars_path: out.join("a_share.csv"),
            industries_path: out.join("a_industries.csv"),
        },
        MarketSpec {
            market: "JP",
            symbols: req.jp_symbols,
            industries: req.industries_per_market,
            bars_path: out.join("jp_equities.csv"),
            industries_path: out.join("jp_industries.csv"),
        },
    ];
    for spec in specs {
        generate_market(&cal, &mut rng, req.start_date, req.end_date, &spec)?;
    }

    let readme = out.join("README.md");
    fs::write(
        &readme,
        format!(
            "# Synthetic Dataset (Generated)\n\n\
Generated by `private-quant-bot gen-synth-data`.\n\n\
Params:\n\
- start_date={}\n\
- end_date={}\n\
- seed={}\n\
- us_symbols={}\n\
- a_symbols={}\n\
- jp_symbols={}\n\
- industries_per_market={}\n\n\
Files:\n\
- us_equities.csv / a_share.csv / jp_equities.csv\n\
  - schema: date,symbol,close,adj_close,volume\n\
- us_industries.csv / a_industries.csv / jp_industries.csv\n\
  - schema: symbol,industry\n",
            req.start_date,
            req.end_date,
            req.seed,
            req.us_symbols,
            req.a_symbols,
            req.jp_symbols,
            req.industries_per_market
        ),
    )?;

    Ok(())
}

#[derive(Debug, Clone)]
struct MarketSpec {
    market: &'static str,
    symbols: usize,
    industries: usize,
    bars_path: PathBuf,
    industries_path: PathBuf,
}

fn generate_market(
    cal: &ExchangeCalendar,
    rng: &mut SplitMix64,
    start: NaiveDate,
    end: NaiveDate,
    spec: &MarketSpec,
) -> Result<()> {
    let sym_prefix = spec.market.to_uppercase();
    let symbol_list = (1..=spec.symbols)
        .map(|i| format!("{sym_prefix}{:03}", i))
        .collect::<Vec<_>>();

    write_industries(&symbol_list, spec.industries, &spec.industries_path)?;
    write_bars(
        cal,
        rng,
        spec.market,
        &symbol_list,
        start,
        end,
        &spec.bars_path,
    )?;
    Ok(())
}

fn write_industries(symbols: &[String], industries: usize, path: &Path) -> Result<()> {
    let mut wtr = csv::Writer::from_path(path)
        .with_context(|| format!("open industries output failed: {}", path.display()))?;
    wtr.write_record(["symbol", "industry"])?;
    for (idx, sym) in symbols.iter().enumerate() {
        let ind = format!("IND{}", idx % industries);
        wtr.write_record([sym.as_str(), ind.as_str()])?;
    }
    wtr.flush()?;
    Ok(())
}

fn write_bars(
    cal: &ExchangeCalendar,
    rng: &mut SplitMix64,
    market: &str,
    symbols: &[String],
    start: NaiveDate,
    end: NaiveDate,
    path: &Path,
) -> Result<()> {
    let mut wtr = csv::Writer::from_path(path)
        .with_context(|| format!("open bars output failed: {}", path.display()))?;
    wtr.write_record(["date", "symbol", "close", "adj_close", "volume"])?;

    // Per-symbol state
    let mut price = symbols
        .iter()
        .map(|s| {
            let base = 30.0 + 170.0 * rng.next_f64();
            (s.clone(), base)
        })
        .collect::<std::collections::HashMap<_, _>>();
    let base_vol = symbols
        .iter()
        .map(|s| {
            let v = 50_000.0 + 1_500_000.0 * rng.next_f64();
            (s.clone(), v)
        })
        .collect::<std::collections::HashMap<_, _>>();

    // Market-level parameters (slightly different regimes by market)
    let (drift, vol) = match market.to_uppercase().as_str() {
        "US" => (0.00025, 0.013),
        "JP" => (0.00015, 0.012),
        "A" => (0.00020, 0.016),
        _ => (0.00020, 0.014),
    };

    let mut d = start;
    while d <= end {
        if !cal.is_trading_day(market, d) {
            d += Duration::days(1);
            continue;
        }

        for sym in symbols {
            let shock = rng.normal();
            let ret = drift + vol * shock;
            let p0 = price.get(sym).copied().unwrap_or(100.0);
            let mut p1 = (p0 * (1.0 + ret)).max(0.5);
            if !p1.is_finite() {
                p1 = p0.max(0.5);
            }
            price.insert(sym.clone(), p1);

            let v0 = base_vol.get(sym).copied().unwrap_or(100_000.0);
            let v_noise = (1.0 + 0.35 * rng.normal()).max(0.0);
            let mut volu = (v0 * v_noise).max(0.0);

            // Small chance of a halt-like day.
            if rng.next_f64() < 0.008 {
                volu = 0.0;
            }

            // For synthetic data, set adj_close == close to keep schema-compatible.
            let close = round_to(p1, 4);
            let adj_close = close;
            let volume = round_to(volu, 2);

            wtr.write_record([
                d.format("%Y-%m-%d").to_string(),
                sym.clone(),
                close.to_string(),
                adj_close.to_string(),
                volume.to_string(),
            ])?;
        }

        d += Duration::days(1);
    }
    wtr.flush()?;
    Ok(())
}

fn round_to(x: f64, dp: i32) -> f64 {
    let m = 10_f64.powi(dp.max(0));
    (x * m).round() / m
}

// Minimal deterministic PRNG for reproducible datasets without extra dependencies.
#[derive(Debug, Clone)]
struct SplitMix64 {
    state: u64,
}

impl SplitMix64 {
    fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    fn next_f64(&mut self) -> f64 {
        // 53-bit precision in [0,1)
        let x = self.next_u64() >> 11;
        (x as f64) / ((1u64 << 53) as f64)
    }

    fn normal(&mut self) -> f64 {
        // Box-Muller
        let u1 = self.next_f64().max(1e-12);
        let u2 = self.next_f64();
        let r = (-2.0 * u1.ln()).sqrt();
        let theta = 2.0 * std::f64::consts::PI * u2;
        r * theta.cos()
    }
}

#[cfg(test)]
mod tests {
    use std::fs;

    use chrono::NaiveDate;
    use sha2::{Digest, Sha256};

    use super::{generate_synth_dataset, SynthDatasetRequest};

    fn sha256_file(path: &std::path::Path) -> String {
        let bytes = fs::read(path).expect("read file");
        let mut h = Sha256::new();
        h.update(&bytes);
        format!("{:x}", h.finalize())
    }

    #[test]
    fn synth_dataset_is_deterministic_for_same_seed() {
        let tmp = std::env::temp_dir().join("pqbot_synth_test");
        let _ = fs::remove_dir_all(&tmp);
        fs::create_dir_all(&tmp).expect("mkdir");

        let req = SynthDatasetRequest {
            output_dir: tmp.join("one"),
            start_date: NaiveDate::from_ymd_opt(2025, 1, 2).unwrap(),
            end_date: NaiveDate::from_ymd_opt(2025, 1, 20).unwrap(),
            seed: 42,
            us_symbols: 2,
            a_symbols: 2,
            jp_symbols: 2,
            industries_per_market: 2,
            force: true,
        };
        generate_synth_dataset(&req).expect("gen one");

        let req2 = SynthDatasetRequest {
            output_dir: tmp.join("two"),
            ..req.clone()
        };
        generate_synth_dataset(&req2).expect("gen two");

        let f1 = req.output_dir.join("us_equities.csv");
        let f2 = req2.output_dir.join("us_equities.csv");
        assert_eq!(sha256_file(&f1), sha256_file(&f2));
    }
}
