use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use chrono::{Duration, NaiveDate};

use crate::calendar::ExchangeCalendar;

#[derive(Debug, Clone)]
pub struct SynthDatasetRequest {
    pub output_dir: PathBuf,
    pub start_date: NaiveDate,
    pub end_date: NaiveDate,
    pub seed: u64,
    pub us_symbols: usize,
    pub a_symbols: usize,
    pub jp_symbols: usize,
    pub industries_per_market: usize,
    pub force: bool,
}

pub fn generate_synth_dataset(req: &SynthDatasetRequest) -> Result<()> {
    if req.start_date > req.end_date {
        return Err(anyhow!("start_date must be <= end_date"));
    }
    if req.industries_per_market == 0 {
        return Err(anyhow!("industries_per_market must be > 0"));
    }
    if req.us_symbols == 0 || req.a_symbols == 0 || req.jp_symbols == 0 {
        return Err(anyhow!("symbol counts must be > 0 for each market"));
    }

    let out = &req.output_dir;
    fs::create_dir_all(out)?;

    let files = [
        out.join("us_equities.csv"),
        out.join("a_share.csv"),
        out.join("jp_equities.csv"),
        out.join("us_industries.csv"),
        out.join("a_industries.csv"),
        out.join("jp_industries.csv"),
    ];
    if !req.force {
        for f in &files {
            if f.exists() {
                return Err(anyhow!(
                    "refusing to overwrite existing file (pass --force): {}",
                    f.display()
                ));
            }
        }
    }

    let cal = ExchangeCalendar::new();
    let mut rng = SplitMix64::new(req.seed);

    let specs = [
        MarketSpec {
            market: "US",
            symbols: req.us_symbols,
            industries: req.industries_per_market,
            bars_path: out.join("us_equities.csv"),
            industries_path: out.join("us_industries.csv"),
        },
        MarketSpec {
            market: "A",
            symbols: req.a_symbols,
            industries: req.industries_per_market,
            bars_path: out.join("a_share.csv"),
            industries_path: out.join("a_industries.csv"),
        },
        MarketSpec {
            market: "JP",
            symbols: req.jp_symbols,
            industries: req.industries_per_market,
            bars_path: out.join("jp_equities.csv"),
            industries_path: out.join("jp_industries.csv"),
        },
    ];
    for spec in specs {
        generate_market(&cal, &mut rng, req.start_date, req.end_date, &spec)?;
    }

    let readme = out.join("README.md");
    fs::write(
        &readme,
        format!(
            "# Synthetic Dataset (Generated)\n\n\
Generated by `private-quant-bot gen-synth-data`.\n\n\
This dataset is still synthetic, but it is designed to be **longer** and **more market-like** than the tiny bootstrap sample used in the earliest versions of the repo.\n\n\
Characteristics:\n\
- multi-year daily history\n\
- market + industry + idiosyncratic return components\n\
- occasional zero-volume / halt-like days\n\
- optional split-like events via `adj_close`\n\
- market-specific symbol shapes and industry labels\n\n\
Params:\n\
- start_date={}\n\
- end_date={}\n\
- seed={}\n\
- us_symbols={}\n\
- a_symbols={}\n\
- jp_symbols={}\n\
- industries_per_market={}\n\n\
Files:\n\
- us_equities.csv / a_share.csv / jp_equities.csv\n\
  - schema: date,symbol,close,adj_close,volume\n\
- us_industries.csv / a_industries.csv / jp_industries.csv\n\
  - schema: symbol,industry\n",
            req.start_date,
            req.end_date,
            req.seed,
            req.us_symbols,
            req.a_symbols,
            req.jp_symbols,
            req.industries_per_market
        ),
    )?;

    Ok(())
}

#[derive(Debug, Clone)]
struct MarketSpec {
    market: &'static str,
    symbols: usize,
    industries: usize,
    bars_path: PathBuf,
    industries_path: PathBuf,
}

#[derive(Debug, Clone)]
struct SymbolProfile {
    symbol: String,
    industry: String,
    start_price: f64,
    base_volume: f64,
    market_beta: f64,
    industry_beta: f64,
    idio_vol: f64,
    drift_bias: f64,
}

#[derive(Debug, Clone, Copy)]
struct MarketDynamics {
    daily_drift: f64,
    market_vol: f64,
    industry_vol: f64,
    halt_chance: f64,
    jump_chance: f64,
    max_abs_return: f64,
    split_chance: f64,
}

fn generate_market(
    cal: &ExchangeCalendar,
    rng: &mut SplitMix64,
    start: NaiveDate,
    end: NaiveDate,
    spec: &MarketSpec,
) -> Result<()> {
    let profiles = build_symbol_profiles(spec, rng);
    write_industries(&profiles, &spec.industries_path)?;
    write_bars(
        cal,
        rng,
        spec.market,
        &profiles,
        start,
        end,
        &spec.bars_path,
    )?;
    Ok(())
}

fn build_symbol_profiles(spec: &MarketSpec, rng: &mut SplitMix64) -> Vec<SymbolProfile> {
    let templates = market_symbol_templates(spec.market);
    let target_industries = spec.industries.max(1);

    (0..spec.symbols)
        .map(|idx| {
            let fallback = fallback_symbol_template(spec.market, idx + 1);
            let template = templates.get(idx).unwrap_or(&fallback);
            let industry = if idx < templates.len() {
                template.1.to_string()
            } else {
                format!("IND{}", idx % target_industries)
            };
            let (start_price, base_volume) = market_price_volume_seed(spec.market, idx, rng);
            SymbolProfile {
                symbol: template.0.to_string(),
                industry,
                start_price,
                base_volume,
                market_beta: 0.8 + 0.5 * rng.next_f64(),
                industry_beta: 0.5 + 0.4 * rng.next_f64(),
                idio_vol: market_idio_vol(spec.market) * (0.8 + 0.5 * rng.next_f64()),
                drift_bias: (rng.next_f64() - 0.5) * market_idio_vol(spec.market) * 0.18,
            }
        })
        .collect()
}

fn write_industries(profiles: &[SymbolProfile], path: &Path) -> Result<()> {
    let mut wtr = csv::Writer::from_path(path)
        .with_context(|| format!("open industries output failed: {}", path.display()))?;
    wtr.write_record(["symbol", "industry"])?;
    for profile in profiles {
        wtr.write_record([profile.symbol.as_str(), profile.industry.as_str()])?;
    }
    wtr.flush()?;
    Ok(())
}

fn write_bars(
    cal: &ExchangeCalendar,
    rng: &mut SplitMix64,
    market: &str,
    profiles: &[SymbolProfile],
    start: NaiveDate,
    end: NaiveDate,
    path: &Path,
) -> Result<()> {
    let mut wtr = csv::Writer::from_path(path)
        .with_context(|| format!("open bars output failed: {}", path.display()))?;
    wtr.write_record(["date", "symbol", "close", "adj_close", "volume"])?;

    let mut price = profiles
        .iter()
        .map(|profile| (profile.symbol.clone(), profile.start_price))
        .collect::<HashMap<_, _>>();
    let mut adj_factor = profiles
        .iter()
        .map(|profile| (profile.symbol.clone(), 1.0))
        .collect::<HashMap<_, _>>();
    let mut industry_state = profiles
        .iter()
        .map(|profile| (profile.industry.clone(), 0.0))
        .collect::<HashMap<_, _>>();
    let dynamics = market_dynamics(market);
    let mut market_state = 0.0;

    let mut d = start;
    while d <= end {
        if !cal.is_trading_day(market, d) {
            d += Duration::days(1);
            continue;
        }

        market_state = 0.88 * market_state + dynamics.market_vol * 0.35 * rng.normal();
        if rng.next_f64() < dynamics.jump_chance {
            market_state +=
                dynamics.market_vol * 1.8 * if rng.next_f64() < 0.5 { -1.0 } else { 1.0 };
        }

        for state in industry_state.values_mut() {
            *state = 0.82 * *state + dynamics.industry_vol * rng.normal();
        }

        for profile in profiles {
            let p0 = price
                .get(&profile.symbol)
                .copied()
                .unwrap_or(profile.start_price)
                .max(0.5);
            let industry_component = industry_state
                .get(&profile.industry)
                .copied()
                .unwrap_or(0.0);
            let mut ret = dynamics.daily_drift
                + market_state * profile.market_beta
                + industry_component * profile.industry_beta
                + profile.drift_bias
                + profile.idio_vol * rng.normal();
            if rng.next_f64() < dynamics.jump_chance * 0.8 {
                ret += profile.idio_vol * 2.2 * if rng.next_f64() < 0.45 { -1.0 } else { 1.0 };
            }
            ret = ret.clamp(-dynamics.max_abs_return, dynamics.max_abs_return);

            let mut raw_close = (p0 * (1.0 + ret)).max(0.5);
            let mut volume =
                (profile.base_volume * (1.0 + ret.abs() * 18.0) * (0.75 + 0.5 * rng.next_f64()))
                    .max(0.0);
            let mut factor = adj_factor.get(&profile.symbol).copied().unwrap_or(1.0);

            if rng.next_f64() < dynamics.halt_chance {
                raw_close = p0;
                volume = 0.0;
            }

            if rng.next_f64() < dynamics.split_chance {
                raw_close *= 0.5;
                factor *= 2.0;
            }

            price.insert(profile.symbol.clone(), raw_close);
            adj_factor.insert(profile.symbol.clone(), factor);

            let close = round_to(raw_close, 4);
            let adj_close = round_to(raw_close * factor, 4);
            let volume = round_to(volume, 2);

            wtr.write_record([
                d.format("%Y-%m-%d").to_string(),
                profile.symbol.clone(),
                close.to_string(),
                adj_close.to_string(),
                volume.to_string(),
            ])?;
        }

        d += Duration::days(1);
    }
    wtr.flush()?;
    Ok(())
}

fn market_symbol_templates(market: &str) -> Vec<(&'static str, &'static str)> {
    match market.to_uppercase().as_str() {
        "US" => vec![
            ("AAPL", "Technology"),
            ("MSFT", "Technology"),
            ("NVDA", "Technology"),
            ("AMZN", "ConsumerDiscretionary"),
            ("GOOGL", "CommunicationServices"),
            ("META", "CommunicationServices"),
            ("JPM", "Financials"),
            ("XOM", "Energy"),
            ("LLY", "Healthcare"),
            ("COST", "ConsumerStaples"),
            ("UNH", "Healthcare"),
            ("HD", "ConsumerDiscretionary"),
        ],
        "A" => vec![
            ("600519", "ConsumerStaples"),
            ("000001", "Financials"),
            ("300750", "Industrials"),
            ("601318", "Financials"),
            ("000333", "ConsumerDiscretionary"),
            ("600036", "Financials"),
            ("002594", "Industrials"),
            ("600276", "Healthcare"),
            ("000858", "ConsumerStaples"),
            ("601899", "Materials"),
            ("600030", "Financials"),
            ("600887", "ConsumerStaples"),
        ],
        "JP" => vec![
            ("7203", "Automotive"),
            ("6758", "Technology"),
            ("9984", "CommunicationServices"),
            ("8306", "Financials"),
            ("8035", "Technology"),
            ("6501", "Industrials"),
            ("9432", "CommunicationServices"),
            ("6861", "Technology"),
            ("4063", "Materials"),
            ("6098", "Industrials"),
            ("7974", "ConsumerDiscretionary"),
            ("7267", "Automotive"),
        ],
        _ => Vec::new(),
    }
}

fn fallback_symbol_template(market: &str, idx: usize) -> (&'static str, &'static str) {
    let fallback = match market.to_uppercase().as_str() {
        "US" => format!("US{:03}", idx),
        "A" => format!("{:06}", 600000 + idx as i32),
        "JP" => format!("{:04}", 7000 + idx as i32),
        _ => format!("SYM{:03}", idx),
    };
    let leaked = Box::leak(fallback.into_boxed_str());
    (leaked, "IND0")
}

fn market_dynamics(market: &str) -> MarketDynamics {
    match market.to_uppercase().as_str() {
        "US" => MarketDynamics {
            daily_drift: 0.00028,
            market_vol: 0.0105,
            industry_vol: 0.0060,
            halt_chance: 0.0015,
            jump_chance: 0.010,
            max_abs_return: 0.16,
            split_chance: 0.0008,
        },
        "A" => MarketDynamics {
            daily_drift: 0.00022,
            market_vol: 0.0135,
            industry_vol: 0.0080,
            halt_chance: 0.0050,
            jump_chance: 0.014,
            max_abs_return: 0.099,
            split_chance: 0.0002,
        },
        "JP" => MarketDynamics {
            daily_drift: 0.00018,
            market_vol: 0.0115,
            industry_vol: 0.0065,
            halt_chance: 0.0025,
            jump_chance: 0.011,
            max_abs_return: 0.14,
            split_chance: 0.0004,
        },
        _ => MarketDynamics {
            daily_drift: 0.00020,
            market_vol: 0.0120,
            industry_vol: 0.0065,
            halt_chance: 0.0020,
            jump_chance: 0.010,
            max_abs_return: 0.15,
            split_chance: 0.0005,
        },
    }
}

fn market_price_volume_seed(market: &str, idx: usize, rng: &mut SplitMix64) -> (f64, f64) {
    match market.to_uppercase().as_str() {
        "US" => (
            40.0 + idx as f64 * 18.0 + 120.0 * rng.next_f64(),
            1_500_000.0 + 4_500_000.0 * rng.next_f64(),
        ),
        "A" => {
            if idx % 4 == 0 {
                (
                    600.0 + 1_400.0 * rng.next_f64(),
                    150_000.0 + 800_000.0 * rng.next_f64(),
                )
            } else {
                (
                    8.0 + 45.0 * rng.next_f64(),
                    2_000_000.0 + 12_000_000.0 * rng.next_f64(),
                )
            }
        }
        "JP" => (
            1_200.0 + idx as f64 * 180.0 + 4_000.0 * rng.next_f64(),
            300_000.0 + 2_500_000.0 * rng.next_f64(),
        ),
        _ => (
            20.0 + 180.0 * rng.next_f64(),
            100_000.0 + 1_000_000.0 * rng.next_f64(),
        ),
    }
}

fn market_idio_vol(market: &str) -> f64 {
    match market.to_uppercase().as_str() {
        "US" => 0.010,
        "A" => 0.016,
        "JP" => 0.011,
        _ => 0.012,
    }
}

fn round_to(x: f64, dp: i32) -> f64 {
    let m = 10_f64.powi(dp.max(0));
    (x * m).round() / m
}

// Minimal deterministic PRNG for reproducible datasets without extra dependencies.
#[derive(Debug, Clone)]
struct SplitMix64 {
    state: u64,
}

impl SplitMix64 {
    fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    fn next_f64(&mut self) -> f64 {
        // 53-bit precision in [0,1)
        let x = self.next_u64() >> 11;
        (x as f64) / ((1u64 << 53) as f64)
    }

    fn normal(&mut self) -> f64 {
        // Box-Muller
        let u1 = self.next_f64().max(1e-12);
        let u2 = self.next_f64();
        let r = (-2.0 * u1.ln()).sqrt();
        let theta = 2.0 * std::f64::consts::PI * u2;
        r * theta.cos()
    }
}

#[cfg(test)]
mod tests {
    use std::fs;

    use chrono::NaiveDate;
    use sha2::{Digest, Sha256};

    use super::{generate_synth_dataset, SynthDatasetRequest};

    fn sha256_file(path: &std::path::Path) -> String {
        let bytes = fs::read(path).expect("read file");
        let mut h = Sha256::new();
        h.update(&bytes);
        format!("{:x}", h.finalize())
    }

    #[test]
    fn synth_dataset_is_deterministic_for_same_seed() {
        let tmp = std::env::temp_dir().join("pqbot_synth_test");
        let _ = fs::remove_dir_all(&tmp);
        fs::create_dir_all(&tmp).expect("mkdir");

        let req = SynthDatasetRequest {
            output_dir: tmp.join("one"),
            start_date: NaiveDate::from_ymd_opt(2025, 1, 2).unwrap(),
            end_date: NaiveDate::from_ymd_opt(2025, 1, 20).unwrap(),
            seed: 42,
            us_symbols: 2,
            a_symbols: 2,
            jp_symbols: 2,
            industries_per_market: 2,
            force: true,
        };
        generate_synth_dataset(&req).expect("gen one");

        let req2 = SynthDatasetRequest {
            output_dir: tmp.join("two"),
            ..req.clone()
        };
        generate_synth_dataset(&req2).expect("gen two");

        let f1 = req.output_dir.join("us_equities.csv");
        let f2 = req2.output_dir.join("us_equities.csv");
        assert_eq!(sha256_file(&f1), sha256_file(&f2));
    }
}
